/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.codechix.onf_driver;

public final class cc_ofver_e {
  public final static cc_ofver_e CC_OFVER_1_0 = new cc_ofver_e("CC_OFVER_1_0", cc_of_driver_javaJNI.CC_OFVER_1_0_get());
  public final static cc_ofver_e CC_OFVER_1_3 = new cc_ofver_e("CC_OFVER_1_3");
  public final static cc_ofver_e CC_OFVER_1_3_1 = new cc_ofver_e("CC_OFVER_1_3_1");
  public final static cc_ofver_e MAX_OFVER_TYPE = new cc_ofver_e("MAX_OFVER_TYPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static cc_ofver_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + cc_ofver_e.class + " with value " + swigValue);
  }

  private cc_ofver_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private cc_ofver_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private cc_ofver_e(String swigName, cc_ofver_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static cc_ofver_e[] swigValues = { CC_OFVER_1_0, CC_OFVER_1_3, CC_OFVER_1_3_1, MAX_OFVER_TYPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

