/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "stdint.h"
#include "../cc_of_lib.h"


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_SEND_1MSG_1BUF_1SIZE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(1024);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_SEND_1MSG_1BUF_1set(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  char *arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return ;
  }
  {
    if(arg1) {
      strncpy((char*)SEND_MSG_BUF, (const char *)arg1, 1024-1);
      SEND_MSG_BUF[1024-1] = 0;
    } else {
      SEND_MSG_BUF[0] = 0;
    }
  }
  
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
}


SWIGEXPORT jstring JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_SEND_1MSG_1BUF_1get(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)(char *)SEND_MSG_BUF;
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(0);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1ESYS_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1EINVAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1EAGAIN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1ENOMEM_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1MDEV_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1EHTBL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1MCHANN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1ECHANN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-8);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1EEXIST_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-9);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OF_1EMISC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)(-10);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1errtable_1get(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  char **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char **)(char **)cc_of_errtable;
  *(char ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1strerror(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jstring jresult = 0 ;
  int arg1 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (char *)cc_of_strerror(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_CC_1OFVER_11_10_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum cc_ofver_ result;
  
  (void)jenv;
  (void)jcls;
  result = (enum cc_ofver_)CC_OFVER_1_0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_TCP_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum L4_type_ result;
  
  (void)jenv;
  (void)jcls;
  result = (enum L4_type_)TCP;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_SWITCH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  enum of_dev_type_ result;
  
  (void)jenv;
  (void)jcls;
  result = (enum of_dev_type_)SWITCH;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1lib_1init(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  of_dev_type_e arg1 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (of_dev_type_e)jarg1; 
  result = (cc_of_ret)cc_of_lib_init(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1lib_1free(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  result = (cc_of_ret)cc_of_lib_free();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1dev_1register(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jint jarg4, jlong jarg5, jlong jarg6, jlong jarg7) {
  jint jresult = 0 ;
  uint32_t arg1 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  cc_ofver_e arg4 ;
  cc_of_recv_pkt arg5 = (cc_of_recv_pkt) 0 ;
  cc_of_accept_channel arg6 = (cc_of_accept_channel) 0 ;
  cc_of_delete_channel arg7 = (cc_of_delete_channel) 0 ;
  uint32_t *argp1 ;
  uint32_t *argp2 ;
  uint16_t *argp3 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint32_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint32_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return 0;
  }
  arg3 = *argp3; 
  arg4 = (cc_ofver_e)jarg4; 
  arg5 = *(cc_of_recv_pkt *)&jarg5; 
  arg6 = *(cc_of_accept_channel *)&jarg6; 
  arg7 = *(cc_of_delete_channel *)&jarg7; 
  result = (cc_of_ret)cc_of_dev_register(arg1,arg2,arg3,arg4,arg5,arg6,arg7);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1dev_1free(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3) {
  jint jresult = 0 ;
  uint32_t arg1 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  uint32_t *argp1 ;
  uint32_t *argp2 ;
  uint16_t *argp3 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint32_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint32_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return 0;
  }
  arg3 = *argp3; 
  result = (cc_of_ret)cc_of_dev_free(arg1,arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1create_1channel(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5, jint jarg6) {
  jint jresult = 0 ;
  uint32_t arg1 ;
  uint32_t arg2 ;
  uint16_t arg3 ;
  uint64_t arg4 ;
  uint8_t arg5 ;
  L4_type_e arg6 ;
  uint32_t *argp1 ;
  uint32_t *argp2 ;
  uint16_t *argp3 ;
  uint64_t *argp4 ;
  uint8_t *argp5 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint32_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint32_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint32_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint16_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint16_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(uint64_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg4 = *argp4; 
  argp5 = *(uint8_t **)&jarg5; 
  if (!argp5) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg5 = *argp5; 
  arg6 = (L4_type_e)jarg6; 
  result = (cc_of_ret)cc_of_create_channel(arg1,arg2,arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1destroy_1channel(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2) {
  jint jresult = 0 ;
  uint64_t arg1 ;
  uint8_t arg2 ;
  uint64_t *argp1 ;
  uint8_t *argp2 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint64_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg2 = *argp2; 
  result = (cc_of_ret)cc_of_destroy_channel(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1send_1pkt(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  uint64_t arg1 ;
  uint8_t arg2 ;
  void *arg3 = (void *) 0 ;
  size_t arg4 ;
  uint64_t *argp1 ;
  uint8_t *argp2 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint64_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(void **)&jarg3; 
  arg4 = (size_t)jarg4; 
  result = (cc_of_ret)cc_of_send_pkt(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1set_1real_1dpid_1auxid(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4) {
  jint jresult = 0 ;
  uint64_t arg1 ;
  uint8_t arg2 ;
  uint64_t arg3 ;
  uint8_t arg4 ;
  uint64_t *argp1 ;
  uint8_t *argp2 ;
  uint64_t *argp3 ;
  uint8_t *argp4 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint64_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg2 = *argp2; 
  argp3 = *(uint64_t **)&jarg3; 
  if (!argp3) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg3 = *argp3; 
  argp4 = *(uint8_t **)&jarg4; 
  if (!argp4) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg4 = *argp4; 
  result = (cc_of_ret)cc_of_set_real_dpid_auxid(arg1,arg2,arg3,arg4);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1get_1conn_1stats(JNIEnv *jenv, jclass jcls, jlong jarg1, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  jint jresult = 0 ;
  uint64_t arg1 ;
  uint8_t arg2 ;
  uint32_t *arg3 = (uint32_t *) 0 ;
  uint32_t *arg4 = (uint32_t *) 0 ;
  uint32_t *arg5 = (uint32_t *) 0 ;
  uint64_t *argp1 ;
  uint8_t *argp2 ;
  cc_of_ret result;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(uint64_t **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint64_t");
    return 0;
  }
  arg1 = *argp1; 
  argp2 = *(uint8_t **)&jarg2; 
  if (!argp2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null uint8_t");
    return 0;
  }
  arg2 = *argp2; 
  arg3 = *(uint32_t **)&jarg3; 
  arg4 = *(uint32_t **)&jarg4; 
  arg5 = *(uint32_t **)&jarg5; 
  result = (cc_of_ret)cc_of_get_conn_stats(arg1,arg2,arg3,arg4,arg5);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1debug_1toggle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gboolean arg1 ;
  gboolean *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(gboolean **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null gboolean");
    return ;
  }
  arg1 = *argp1; 
  cc_of_debug_toggle(arg1);
}


SWIGEXPORT void JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1log_1toggle(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  gboolean arg1 ;
  gboolean *argp1 ;
  
  (void)jenv;
  (void)jcls;
  argp1 = *(gboolean **)&jarg1; 
  if (!argp1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Attempt to dereference null gboolean");
    return ;
  }
  arg1 = *argp1; 
  cc_of_log_toggle(arg1);
}


SWIGEXPORT jstring JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1log_1read(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)cc_of_log_read();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_org_codechix_onf_1driver_cc_1of_1driver_1javaJNI_cc_1of_1log_1clear(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  cc_of_log_clear();
}


#ifdef __cplusplus
}
#endif

