/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.codechix.onf_driver;

public interface cc_of_driver_javaConstants {
  public final static int SEND_MSG_BUF_SIZE = cc_of_driver_javaJNI.SEND_MSG_BUF_SIZE_get();
  public final static int CC_OF_OK = cc_of_driver_javaJNI.CC_OF_OK_get();
  public final static int CC_OF_ESYS = cc_of_driver_javaJNI.CC_OF_ESYS_get();
  public final static int CC_OF_EINVAL = cc_of_driver_javaJNI.CC_OF_EINVAL_get();
  public final static int CC_OF_EAGAIN = cc_of_driver_javaJNI.CC_OF_EAGAIN_get();
  public final static int CC_OF_ENOMEM = cc_of_driver_javaJNI.CC_OF_ENOMEM_get();
  public final static int CC_OF_MDEV = cc_of_driver_javaJNI.CC_OF_MDEV_get();
  public final static int CC_OF_EHTBL = cc_of_driver_javaJNI.CC_OF_EHTBL_get();
  public final static int CC_OF_MCHANN = cc_of_driver_javaJNI.CC_OF_MCHANN_get();
  public final static int CC_OF_ECHANN = cc_of_driver_javaJNI.CC_OF_ECHANN_get();
  public final static int CC_OF_EEXIST = cc_of_driver_javaJNI.CC_OF_EEXIST_get();
  public final static int CC_OF_EMISC = cc_of_driver_javaJNI.CC_OF_EMISC_get();
}
