/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.codechix.onf_driver;

public class cc_of_driver_javaJNI {
  public final static native int SEND_MSG_BUF_SIZE_get();
  public final static native void SEND_MSG_BUF_set(String jarg1);
  public final static native String SEND_MSG_BUF_get();
  public final static native int CC_OF_OK_get();
  public final static native int CC_OF_ESYS_get();
  public final static native int CC_OF_EINVAL_get();
  public final static native int CC_OF_EAGAIN_get();
  public final static native int CC_OF_ENOMEM_get();
  public final static native int CC_OF_MDEV_get();
  public final static native int CC_OF_EHTBL_get();
  public final static native int CC_OF_MCHANN_get();
  public final static native int CC_OF_ECHANN_get();
  public final static native int CC_OF_EEXIST_get();
  public final static native int CC_OF_EMISC_get();
  public final static native long cc_of_errtable_get();
  public final static native String cc_of_strerror(int jarg1);
  public final static native int CC_OFVER_1_0_get();
  public final static native int TCP_get();
  public final static native int SWITCH_get();
  public final static native int cc_of_lib_init(int jarg1);
  public final static native int cc_of_lib_free();
  public final static native int cc_of_dev_register(long jarg1, long jarg2, long jarg3, int jarg4, long jarg5, long jarg6, long jarg7);
  public final static native int cc_of_dev_free(long jarg1, long jarg2, long jarg3);
  public final static native int cc_of_create_channel(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5, int jarg6);
  public final static native int cc_of_destroy_channel(long jarg1, long jarg2);
  public final static native int cc_of_send_pkt(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int cc_of_set_real_dpid_auxid(long jarg1, long jarg2, long jarg3, long jarg4);
  public final static native int cc_of_get_conn_stats(long jarg1, long jarg2, long jarg3, long jarg4, long jarg5);
  public final static native void cc_of_debug_toggle(long jarg1);
  public final static native void cc_of_log_toggle(long jarg1);
  public final static native String cc_of_log_read();
  public final static native void cc_of_log_clear();
}
