/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.codechix.onf_driver;

public final class L4_type_e {
  public final static L4_type_e TCP = new L4_type_e("TCP", cc_of_driver_javaJNI.TCP_get());
  public final static L4_type_e TLS = new L4_type_e("TLS");
  public final static L4_type_e UDP = new L4_type_e("UDP");
  public final static L4_type_e DTLS = new L4_type_e("DTLS");
  public final static L4_type_e MAX_L4_TYPE = new L4_type_e("MAX_L4_TYPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static L4_type_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + L4_type_e.class + " with value " + swigValue);
  }

  private L4_type_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private L4_type_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private L4_type_e(String swigName, L4_type_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static L4_type_e[] swigValues = { TCP, TLS, UDP, DTLS, MAX_L4_TYPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

