/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.codechix.onf_driver;

public final class of_dev_type_e {
  public final static of_dev_type_e SWITCH = new of_dev_type_e("SWITCH", cc_of_driver_javaJNI.SWITCH_get());
  public final static of_dev_type_e CONTROLLER = new of_dev_type_e("CONTROLLER");
  public final static of_dev_type_e MAX_OF_DEV_TYPE = new of_dev_type_e("MAX_OF_DEV_TYPE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static of_dev_type_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + of_dev_type_e.class + " with value " + swigValue);
  }

  private of_dev_type_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private of_dev_type_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private of_dev_type_e(String swigName, of_dev_type_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static of_dev_type_e[] swigValues = { SWITCH, CONTROLLER, MAX_OF_DEV_TYPE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

